Second revision of new compset run scripts.

diff --git a/scripts/compsets/config/checks b/scripts/compsets/config/checks
--- a/scripts/compsets/config/checks
+++ b/scripts/compsets/config/checks
@@ -5,7 +5,7 @@ echo "running checks for $FMID"
 echo $TASKS
 # basic directory/executable checks
 for var in SIGHDR SFCHDR NEMSIOGET APRUN PERL NDATE FIXGLOBAL BASE_NEMS FCSTEXEC EXGLOBALFCSTSH MTNVAR O3FORC O3CLIM \
-	   OROGRAPHY OROGRAPHY_UF LONSPERLAT LONSPERLAR AEROSOL_FILE EMMISSIVITY_FILE ; do
+	   OROGRAPHY OROGRAPHY_UF LONSPERLAT LONSPERLAR ; do
 	eval val=\$$var	# get the value ($val) of the variable that $var references
 	echo "checking for $var: $val"
 	if [ -z $val ] || [ ! -e $val ] ; then # makes sure the variable has been set and the path/file exists
@@ -17,11 +17,43 @@ for var in SIGHDR SFCHDR NEMSIOGET APRUN PERL NDATE FIXGLOBAL BASE_NEMS FCSTEXEC
 	fi
 done
 
-# user.config check
-echo "checking that FHOUT ($FHOUT) is <= FHMAX ($FHMAX)"
+# frequency checks
+echo "checking properties of the frequency options (FHOUT, FHRES, FHDFI, FHCYC, FHZER)"
 if [ -z $FHOUT ] || [ $FHOUT -gt $FHMAX ] ; then
 	echo "   FHOUT is invalid, setting to $FHMAX"
 	export FHOUT=$FHMAX
+fi
+# rule 1: positive DELTIM
+if [ -z $DELTIM ] || [ $DELTIM -le 0 ] ; then
+	echo "   invalid DELTIM (must be positive)! exiting." ; exit 1
+fi
+# rule 2: FHOUT positive, multiple of DELTIM to within $tol
+if [ -z $FHOUT ] || [ $FHOUT -le 0 ] || [ $(((FHOUT*3600%DELTIM)/DELTIM)) != 0 ] ; then
+	echo "   FHOUT invalid: must be positive and a multiple of DELTIM! exiting." ; exit 1
+fi
+# rule 3: FHSWR positive, multiple of DELTIM to within $tol
+if [ -z $FHSWR ] || [ $FHSWR -le 0 ] || [ $(((FHSWR%DELTIM)/DELTIM)) != 0 ] ; then
+	echo "   FHSWR invalid: must be positive and a multiple of DELTIM! exiting." ; exit 1
+fi
+# rule 4: FHLWR, same as rule 3, but also a multiple of FHSWR
+if [ -z $FHLWR ] || [ $FHLWR -le 0 ] || [ $(((FHLWR%DELTIM)/DELTIM)) != 0 ] || [ $((FHLWR%FHSWR)) != 0 ] ; then
+	echo "   FHLWR invalid: must be positive, a multiple of DELTIM, and a multiple of FHSWR! exiting." ; exit 1
+fi
+# rule 5: FHZER, same as rule 3, but also a multiple of FHOUT
+if [ -z $FHZER ] || [ $FHZER -le 0 ] || [ $(((FHZER*3600%DELTIM)/DELTIM)) != 0 ] || [ $((FHZER%FHOUT)) != 0 ] ; then
+	echo "   FHZER invalid: must be positive, a multiple of DELTIM, and a multiple of FHOUT! exiting." ; exit 1
+fi
+# rule 6: FHRES, same as rule 3, but also a multiple of FHLWR and FHZER
+if [ -z $FHRES ] || [ $FHRES -le 0 ] || [ $(((FHRES*3600%DELTIM)/DELTIM)) != 0 ] || [ $((FHRES*3600%FHLWR)) != 0 ] || [ $((FHRES%FHZER)) != 0 ] ; then
+	echo "   FHRES invalid: must be positive, a multiple of DELTIM, FHLWR, and FHZER! exiting." ; exit 1
+fi
+# rule 7: FHDFI, same as rule 3, but also a multiple of FHLWR and <= FHRES
+if [ -z $FHDFI ] || [ $FHDFI -lt 0 ] || [ $(((FHDFI*3600%DELTIM)/DELTIM)) != 0 ] || [ $((FHDFI*3600%FHLWR)) != 0 ] || [ $FHDFI -gt $FHRES ] ; then
+	echo "   FHDFI invalid: must be non-negative, a multiple of DELTIM, FHLWR, and <= FHRES! exiting." ; exit 1
+fi
+# rule 8: FHCYC, same as rule 3, but also a multiple of FHLWR
+if [ -z $FHCYC ] || [ $FHCYC -lt 0 ] || [ $(((FHCYC%DELTIM)/DELTIM)) != 0 ] || [ $((FHCYC*3600%FHLWR)) != 0 ] ; then
+	echo "   FHCYC invalid: must be non-negative, a multiple of DELTIM, and a multiple of FHLWR! exiting." ; exit 1
 fi
 
 # wam.config checks
@@ -42,6 +74,12 @@ if [ $IDEA = .true. ] ; then
 
 	# ipe.config checks
 	if [ $WAM_IPE_COUPLING = .true. ] ; then
+		echo "checking to make sure NPROCIPE is valid: $NPROCIPE"
+		valid=0
+		for i in "${VALID_IPE_PET[@]}" ; do
+			if [ $NPROCIPE = $i ] ; then valid=1 ; fi
+		done
+		[ $valid = 0 ] && echo "   could not match NPROCIPE against the list of allowed configurations, check ipe.config! exiting." && exit 1
 		if [ ! -z $IPEDATETIME ] ; then
 			echo "checking to make sure IPEDATETIME is a valid length: $IPEDATETIME"
 			if [ ${#IPEDATETIME} != 12 ] ; then # also y10k problem!
